### ISSUE TITLE
can't open in macOS 13.4.1

### ISSUE THREAD

**Issue by satchel9** [jimeh/homebrew-emacs-builds#1]
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libwebp.7.dylib
/Applications/Emacs.app/Contents/Frameworks/libwebpdemux.2.dylib
Reason: tried: '/Applications/Emacs.app/Contents/Frameworks/../lib/libwebp.7.dylib' (no such file), '/Applications/Emacs.app/Contents/Frameworks/libwebp.7.dylib' (no such file), '/Applications/Emacs.app/Contents/Frameworks/libwebp.7.dylib' (no such file), '/usr/lib/libwebp.7.dylib' (no such file, not in dyld cache)

**Comment by igorepst** [comment]
Try `brew install webp`

**Comment by jimeh** [comment]
The upstream issue is https://github.com/jimeh/emacs-builds/issues/25. I've got a [fix](https://github.com/jimeh/build-emacs-for-macos/pull/88) in the underlying build script, so this should be resolved in the next few days.

**Comment by jimeh** [comment]
This should now be resolved. Any builds after November 19th should no longer have this issue.
